Improve base module cardtypes, fieldtypes, templates and workflows
CyberismoCom/module-base pull request #7
Opened 2024-11-09 13:34 UTC by suvikaartinen

Please review and give your feedback.

2024-11-11 11:02 UTC, henryhaverinen requested changes

2024-11-11 11:04 UTC, suvikaartinen commented on .cards/local/fieldTypes/informationClassification.json
> +    "dataType": "enum",
We discussed this and agreed to continue with this enum.

2024-11-11 11:05 UTC, suvikaartinen commented on .cards/local/templates/controlledDocument/c/base_5/index.adoc
> +This document describes __TODO: addshort description___
Let's create a new template for process description and keep the original controlled document as short as possible.

2024-11-11 11:07 UTC, suvikaartinen commented on .cards/local/reports/childrenList/index.adoc.hbs
> -* xref:{{this.key}}.adoc[{{this.title}}]
Let's create a new childrenTable version for this and keep the original.

2024-11-11 11:08 UTC, suvikaartinen commented on .cards/local/cardTypes/recurringTask.json
> +            "name": "base/fieldTypes/reviewPeriod"
I agree. Let's change this.

2024-11-11 14:02 UTC, suvikaartinen commented on .cards/local/templates/controlledDocument/c/base_5/index.adoc
> +This document describes __TODO: addshort description___
New commit created.

2024-11-11 14:03 UTC, suvikaartinen commented on .cards/local/cardTypes/recurringTask.json
> +            "name": "base/fieldTypes/reviewPeriod"
New commit created.

2024-11-11 14:03 UTC, suvikaartinen commented on .cards/local/reports/childrenList/index.adoc.hbs
> -* xref:{{this.key}}.adoc[{{this.title}}]
New commit created.

2024-11-11 15:16 UTC, henryhaverinen approved these changes
Looks great! If you like, you could still improve the report.json for the new children table report.

2024-11-11 15:16 UTC, henryhaverinen commented on .cards/local/reports/childrenTable/report.json
> +  "displayName": "Example report",
This could be "A table of child cards"

2024-11-11 15:16 UTC, henryhaverinen commented on .cards/local/reports/childrenTable/report.json
> +  "category": "Uncategorised report"
This could be "General"

2024-11-11 15:16 UTC, henryhaverinen commented on .cards/local/reports/childrenTable/report.json
> +  "description": "A description of the example report",
For example: "A table of child cards with columns for owner and workflow state"

2024-11-12 06:12 UTC, Fuzzbender commented on .cards/local/cardTypes/controlledDocument.json
> +            "name": "base/fieldTypes/approver"
No need to do in this PR, but I think all of the resources should be listed by 'name' in alphabetical order. 
We can make a separate PR to order them. This makes finding correct value easier.

2024-11-12 06:16 UTC, Fuzzbender commented on .cards/local/templates/processDescription/c/base_ecdl1c2j/index.adoc
> +[1] DIRECTIVE (EU) 2022/2555 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL of 14 December 2022 on measures for a high common level of cybersecurity across the Union
These references are a bit odd here. They are not referred from the boilerplate text. I would remove them.

2024-11-12 06:16 UTC, Fuzzbender approved these changes

2024-11-12 08:37 UTC, merged